IF  NOT EXISTS (SELECT * FROM sys.objects 
WHERE object_id = OBJECT_ID(N'[dbo].[ProductCategory]') AND type in (N'U'))

BEGIN
CREATE TABLE [dbo].[ProductCategory](
	PRODCAT_ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	PRODCAT_Code VARCHAR(20) NOT NULL,
	PRODCAT_Name VARCHAR(30) NOT NULL,
	PRODCAT_ShortDesc VARCHAR(200) NULL
) 

END