IF  NOT EXISTS (SELECT * FROM sys.objects 
WHERE object_id = OBJECT_ID(N'[dbo].[CustomerAddress]') AND type in (N'U'))

BEGIN
CREATE TABLE [dbo].[CustomerAddress](
	CUSTADDR_ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	CUSTADDR_CustID UNIQUEIDENTIFIER NOT NULL,
	CUSTADDR_AddressLine1 VARCHAR(20) NOT NULL,
	CUSTADDR_AddressLine2 VARCHAR(20) NULL,
	CUSTADDR_PostCode VARCHAR(10) NOT NULL,
	CUSTADDR_TownCity VARCHAR(20) NOT NULL,
	CUSTADDR_Province VARCHAR(20) NOT NULL,
	CUSTADDR_Country VARCHAR(20) NOT NULL
) 

END