IF  NOT EXISTS (SELECT * FROM sys.objects 
WHERE object_id = OBJECT_ID(N'[dbo].[ProductDetails]') AND type in (N'U'))

BEGIN
CREATE TABLE [dbo].[ProductDetails](
	PROD_ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	PROD_PRODCAT_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES ProductCategory(PRODCAT_ID),
	PROD_Code VARCHAR(20) NOT NULL,
	PROD_BrandName VARCHAR(30) NOT NULL,
	PROD_Name VARCHAR(60) NOT NULL,
	PROD_ShortDesc VARCHAR(500) NULL,
	PROD_LongDesc VARCHAR(2000) NULL,
	PROD_BuyCost INT NULL,
	PROD_SellCost INT NOT NULL
) 

END


